version: "3.7"
services:
  app:
    build:
      args:
        user: mpemburn
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: asw-roster
    container_name: asw-roster
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - asw-roster

  db:
    image: mysql:5.7
    container_name: asw-roster-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - asw-roster

  nginx:
    image: nginx:alpine
    container_name: asw-roster-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - asw-roster

  php:
    image: php:7.4
    volumes:
      - ./docker-compose/php:/usr/local/etc/php/conf.d

networks:
  asw-roster:
    driver: bridge
