- hosts: "{{ env }}"
  become: yes
  become_user: root
  vars:
    ansible_user: ubuntu

  tasks:
    - name: Install Packages
      apt:
        name: "{{ packages }}"
      vars:
        packages:
          - mariadb-server
          - ccrypt
          - unzip
