- hosts: "{{ env }}"
  become: yes
  become_user: root
  gather_facts: false
  vars:
    ansible_user: ubuntu

  tasks:
    - name: Add PHP 7 PPA Repo
      become: true
      apt_repository:
        repo: 'ppa:ondrej/php'

    - name: Install PHP 7.4 Packages
      apt:
        name: "{{ packages }}"
      vars:
        packages:
          - php7.4-fpm
          - php7.4-curl
          - php7.4-gd
          - php7.4-intl
          - php7.4-mysql
          - php7.4-xml
          - php7.4-xmlrpc
          - php7.4-ldap
          - php7.4-zip
          - php7.4-soap
          - php7.4-mbstring
          - php7.4-pspell
          - php7.4-cli
